### ISSUE TITLE
Question: What is the simplest way to connect and fxparam/name

### ISSUE THREAD

**Issue by betov75** [lucianoiam/pyreaosc#1]
Hi Luciano,
Thank you very much for your very elegant and well designed script. I'm new to Python but I can easily recognize the wit behind it! I'm working on a control surface text-to-speech reader for the blind. I'm well advanced but my connection to OSC is bad. I'm not good at it. Your script is super smooth. For a strange reason, mine needs to be connected to the web with python-osc. I'm quite green.
Using your platform, what is the simplest way to send a OSC message to Reaper and listen to what's getting in? I'm navigating through your script and there are a lot of different connections, since i'm legally blind, it gets tough to follow.
Also, in my script, I retrieve the fxparam/name, can I do the same with yours? Not only the number?
Thanks again!

**Comment by lucianoiam** [comment]
Hi,

The client does not officially expose APIs to deal with custom OSC but you can call `send()` in the client's channel object. See https://github.com/lucianoiam/pyreaosc/blob/master/src/base/channel.py

```
reaper = ReaperClient()
reaper.channel.send('/some/path', arg0, arg1, ...)
```

For receiving OSC you may subclass `ReaperClient` and override `handle_osc()`.

If all you need is just a bidirectional raw connection to REAPER you might leverage `OscChannel` for your project.

FX parameter name is available through the `name` getter in FxParameter though it is currently broken and returns an empty string. There is a relevant comment here https://github.com/lucianoiam/pyreaosc/blob/7c91f33342df5926fb4b71b13d5450ef416f4be5/src/component/fx.py#L74 . Any help on a solution for this is appreciated.

**Comment by betov75** [comment]
Hi Luciano,

Thank you very much for that very detailed and perfectly useful answer.
It's all I needed to test.
I need to say that your programming is a great tutorial for a python
beginner like me. No better way to understand object oriented programming
than dealing with a well known concept for me, like mixer, tracks, fx..
Your script is so neat. It will be extremely useful for my next project; a
MCU accessible interpreter. With all the credits well displayed, of course.

That said, Reaper is strange. Your script is not broken at all; Reaper
don't seem to send FX parameters names and value strings on local port. The
only way I can get them is by using two ports,using the Configure Device
IP + Local Port mode in OSC control surface window. Then, I use my local
port for both, the same client port and another one for the 'device'. So,
my script, using python-osc, sends on a port and receives on another one. I
can have access to way more details, like the /fxparam/name and
/fxparam/valstr etc..

To receive all the info from Reaper, I send
"/device/track/follows/last_touched" and then, the 'device' ip (which is my
script) receiveds everything. Blind composers work by the track. To my
limited knowledge, Reaper don't send /track/selected/ when out of the bank
in local port but not on the device port. I detect that, send the string
previously mentioned and my script is refreshed with all info each time I
change tracks, even when out of the bank range.

Being a better coder, I'll do something directly in Reaper using a dll, but
i'm not.

Hope it helps!



Le lun. 16 nov. 2020 à 03:41, Luciano Iam <notifications@github.com> a
écrit :

**Comment by lucianoiam** [comment]
Sending `/device/track/follows/last_touched` tells REAPER to start returning some information about parameters "on demand", ie. when the user clicks on a parameter control:

Tx:
```
/device/track/follows/last_touched
```

_... user clicks track 1, fx 1, parameter 1 ..._

Rx:
```
/fx/last_touched/track/name ('Track 1',)
/fx/last_touched/track/number/str ('1',)
/fx/last_touched/name ('AGain (Company Name)',)
/fx/last_touched/number/str ('1',)
/fxparam/last_touched/name ('Gain',)
```

This information is enough for identifying parameters visually but unfortunately there is no `/fxparam/last_touched/number/str` so it is impossible to map indexed parameters (or in turn pyreaosc FxParameter instances) to names.

Maybe there is a way to map the loaded project parameters to some of the feedback messages sent by REAPER, through "OSC config files" (Control/OSC/web->Edit->Pattern config->open config directory). Feedback messages like `/fxparam/1/name` and `/fxparam/1/value` are sent in response to `/action (41743)` (the trick pyreaosc uses to fetch initial status -- complete list here https://wiki.cockos.com/wiki/index.php/Action_List_Reference), though they contain empty values, probably that is controlled by such config files. Complete response of _action 41743 / Control surface: refresh all surfaces_ here  https://github.com/lucianoiam/pyreaosc/blob/master/doc/osc_dump.txt#L106 .

Cheers
